#!/usr/bin/env bash
# Pulls the DB/Redis/SQS values that Terraform generated (and stored in AWS
# Secrets Manager / outputs) and materializes them as the Kubernetes Secret
# that the GitOps manifests expect (gitops/base/secrets.yaml only ships a
# placeholder — real values never go into git).
#
# Deliberately kept out of Argo CD's sync scope: secrets are regenerated by
# Terraform on every environment rebuild, so they don't belong in the
# GitOps repo. Run this once after `terraform apply` and again if RDS/Redis
# get recreated.
set -euo pipefail

cd "$(dirname "$0")/.."

AUTH_DB_URL=$(aws secretsmanager get-secret-value --secret-id togglemaster/auth/database-url --query SecretString --output text | jq -r .database_url)
FLAG_DB_URL=$(aws secretsmanager get-secret-value --secret-id togglemaster/flag/database-url --query SecretString --output text | jq -r .database_url)
TARGETING_DB_URL=$(aws secretsmanager get-secret-value --secret-id togglemaster/targeting/database-url --query SecretString --output text | jq -r .database_url)

REDIS_HOST=$(terraform output -raw redis_primary_endpoint)
SQS_URL=$(terraform output -raw sqs_queue_url)
MASTER_KEY=$(openssl rand -hex 32)
SERVICE_API_KEY=$(openssl rand -hex 32)

kubectl create secret generic togglemaster-secrets \
  --namespace togglemaster \
  --from-literal=AUTH_DATABASE_URL="${AUTH_DB_URL}" \
  --from-literal=FLAG_DATABASE_URL="${FLAG_DB_URL}" \
  --from-literal=TARGETING_DATABASE_URL="${TARGETING_DB_URL}" \
  --from-literal=REDIS_URL="redis://${REDIS_HOST}:6379" \
  --from-literal=AWS_SQS_URL="${SQS_URL}" \
  --from-literal=MASTER_KEY="${MASTER_KEY}" \
  --from-literal=SERVICE_API_KEY="${SERVICE_API_KEY}" \
  --dry-run=client -o yaml | kubectl apply -f -

echo "Secret togglemaster-secrets applied to namespace togglemaster."
