services:
  analytics-service:
    build: ./analytics-service
    image: analytics-service:0.1
    restart: always
    ports:
      - "8005:8005"
    environment:
      - PORT=8005
      - AWS_SQS_URL=http://sqs-local:9324/000000000000/auth-analytics
      - AWS_DYNAMODB_TABLE=ToggleMasterAnalytics
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=mockaccesskey
      - AWS_SECRET_ACCESS_KEY=mocksecretkey
    networks:
      - tech-challenger-2-network
  auth-service:
    build: ./auth-service
    image: auth-service:0.1
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:postgres-secret@172.19.0.100:5432,172.19.0.101:5432/auth_db?sslmode=disable&target_session_attrs=read-write
      - PORT=8001
      - MASTER_KEY=supersecretkey
    networks:
      - tech-challenger-2-network
    depends_on:
      postgres-primary:
        condition: service_healthy

  evaluation-service:
    build: ./evaluation-service
    image: evaluation-service:0.1
    restart: always
    ports:
      - "8004:8004"
    environment:
      - PORT=8004
      - REDIS_URL=redis://redis:6379
      - FLAG_SERVICE_URL=http://flag-service:8002
      - TARGETING_SERVICE_URL=http://targeting-service:8003
      - SERVICE_API_KEY=tm_key_2615b64fd5171634efb65691b0c965a1239f0b99fe74078a41488c2eba1ee415
      - AWS_SQS_URL=http://sqs-local:9324/000000000000/auth-analytics
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=mockaccesskey
      - AWS_SECRET_ACCESS_KEY=mocksecretkey
    networks:
      - tech-challenger-2-network
    depends_on:
      - redis
      - flag-service
      - targeting-service

  flag-service:
    build: ./flag-service
    image: flag-service:0.1
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:postgres-secret@172.19.0.100:5432,172.19.0.101:5432/flags_db?target_session_attrs=read-write
      - PORT=8002
      - AUTH_SERVICE_URL=http://auth-service:8001
    networks:
      - tech-challenger-2-network
    depends_on:
      postgres-primary:
        condition: service_healthy

  targeting-service:
    build: ./targeting-service
    image: targeting-service:0.1
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:postgres-secret@172.19.0.100:5432,172.19.0.101:5432/targeting_db?target_session_attrs=read-write
      - PORT=8003
      - AUTH_SERVICE_URL=http://auth-service:8001
    networks:
      - tech-challenger-2-network
    depends_on:
      postgres-primary:
        condition: service_healthy

  sqs-local:
    image: softwaremill/elasticmq-native:latest
    container_name: sqs-local
    ports:
      - "9324:9324"
      - "9325:9325"
    networks:
      - tech-challenger-2-network

  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./databases/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - tech-challenger-2-network

  postgres-primary:
    image: bitnamilegacy/postgresql-repmgr:15
    container_name: postgres-primary
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres-secret
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres-secret
      - POSTGRESQL_DATABASE=auth_db
      - REPMGR_PRIMARY_HOST=172.19.0.100
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=172.19.0.100,172.19.0.101:5432
      - REPMGR_NODE_NAME=postgres-primary-1
      - REPMGR_NODE_ID=1
      - REPMGR_NODE_NETWORK_NAME=172.19.0.100
      - REPMGR_PORT_NUMBER=5432
      - REPMGR_PASSWORD=repl_password
    volumes:
      - postgres-primary-data:/bitnami/postgresql
      - ./auth-service/db/init.sql:/docker-entrypoint-initdb.d/auth_db.sql
      - ./flag-service/db/init.sql:/docker-entrypoint-initdb.d/flags_db.sql
      - ./targeting-service/db/init.sql:/docker-entrypoint-initdb.d/targeting_db.sql
    ports:
      - "5432:5432"
    networks:
      tech-challenger-2-network:
        ipv4_address: 172.19.0.100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d auth_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres-replica:
    image: bitnamilegacy/postgresql-repmgr:15
    container_name: postgres-replica
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres-secret
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres-secret
      - POSTGRESQL_DATABASE=auth_db
      - REPMGR_PRIMARY_HOST=172.19.0.100
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=172.19.0.100,172.19.0.101:5432
      - REPMGR_NODE_NAME=postgres-replica-2
      - REPMGR_NODE_ID=2
      - REPMGR_NODE_NETWORK_NAME=172.19.0.101
      - REPMGR_PORT_NUMBER=5432
      - REPMGR_PASSWORD=repl_password
    volumes:
      - postgres-replica-data:/bitnami/postgresql
    ports:
      - "5433:5432"
    depends_on:
      postgres-primary:
        condition: service_healthy
    networks:
      tech-challenger-2-network:
        ipv4_address: 172.19.0.101

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./databases/redis-data:/data
    networks:
      - tech-challenger-2-network

  nginx-lb:
    image: nginx:alpine
    container_name: nginx-lb
    ports:
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - flag-service
      - targeting-service
    networks:
      - tech-challenger-2-network

networks:
  tech-challenger-2-network:
    ipam:
      config:
        - subnet: 172.19.0.0/16

volumes:
  postgres-primary-data:
  postgres-replica-data:
