apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: togglemaster
  labels:
    app: evaluation-service
spec:
  type: ClusterIP
  ports:
    - port: 8004
      targetPort: 8004
      name: http
  selector:
    app: evaluation-service
