apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: togglemaster
  labels:
    app: analytics-service
    app.kubernetes.io/name: analytics-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      serviceAccountName: togglemaster-workload
      containers:
        - name: analytics-service
          image: 775419744057.dkr.ecr.us-east-1.amazonaws.com/analytics-service:v1.0.0-38a5764
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
              name: http
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: ANALYTICS_SERVICE_PORT
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: AWS_REGION
            - name: AWS_DYNAMODB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: AWS_DYNAMODB_TABLE
            - name: AWS_SQS_URL
              valueFrom:
                secretKeyRef:
                  name: togglemaster-secrets
                  key: AWS_SQS_URL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
