events {
    worker_connections 1024;
}

http {
    # Use Docker's internal DNS server and cache resolution for only 5 seconds
    resolver 127.0.0.11 valid=5s;

    server {
        listen 8001;
        location / {
            set $upstream_auth auth-service:8001;
            proxy_pass http://$upstream_auth;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 8002;
        location / {
            set $upstream_flag flag-service:8002;
            proxy_pass http://$upstream_flag;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 8003;
        location / {
            set $upstream_targeting targeting-service:8003;
            proxy_pass http://$upstream_targeting;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
