apiVersion: v1
kind: Service
metadata:
  name: flag-service
  namespace: togglemaster
  labels:
    app: flag-service
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
      name: http
  selector:
    app: flag-service
