apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-secrets
  namespace: togglemaster
  labels:
    app.kubernetes.io/name: togglemaster
type: Opaque
data:
  # Base64 encoded values:
  # AUTH_DATABASE_URL = postgres://postgres:AALIsRzJ1SiqtB6us@togglemaster-auth-db.cxoi0ssushpo.us-west-1.rds.amazonaws.com:5432/auth_db
  AUTH_DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpBQUxJc1J6SjFTaXF0QjZ1c0B0b2dnbGVtYXN0ZXItYXV0aC1kYi5jeG9pMHNzdXNocG8udXMtd2VzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvYXV0aF9kYg==
  # FLAG_DATABASE_URL = postgres://postgres:AALIsRzJ1SiqtB6us@togglemaster-flag-db.cxoi0ssushpo.us-west-1.rds.amazonaws.com:5432/flags_db
  FLAG_DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpBQUxJc1J6SjFTaXF0QjZ1c0B0b2dnbGVtYXN0ZXItZmxhZy1kYi5jeG9pMHNzdXNocG8udXMtd2VzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvZmxhZ3NfZGI=
  # TARGETING_DATABASE_URL = postgres://postgres:AALIsRzJ1SiqtB6us@togglemaster-targeting-db.cxoi0ssushpo.us-west-1.rds.amazonaws.com:5432/targeting_db
  TARGETING_DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpBQUxJc1J6SjFTaXF0QjZ1c0B0b2dnbGVtYXN0ZXItdGFyZ2V0aW5nLWRiLmN4b2kwc3N1c2hwby51cy13ZXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi90YXJnZXRpbmdfZGI=
  # REDIS_URL = rediss://evaluation-redis-vpc-public-awdbwc.serverless.usw1.cache.amazonaws.com:6379
  REDIS_URL: cmVkaXNzOi8vZXZhbHVhdGlvbi1yZWRpcy12cGMtcHVibGljLWF3ZGJ3Yy5zZXJ2ZXJsZXNzLnVzdzEuY2FjaGUuYW1hem9uYXdzLmNvbTo2Mzc5
  # AWS_SQS_URL = https://sqs.us-west-1.amazonaws.com/775419744057/evaluation-analytics
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtd2VzdC0xLmFtYXpvbmF3cy5jb20vNzc1NDE5NzQ0MDU3L2V2YWx1YXRpb24tYW5hbHl0aWNz
  # MASTER_KEY = supersecretkey
  MASTER_KEY: c3VwZXJzZWNyZXRrZXk=
  # SERVICE_API_KEY = SUA_CHAVE_DE_SERVICO
  SERVICE_API_KEY: U1VBX0NIQVZFX0RFX1NFUlZJQ08=
