apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analytics-service-scaledobject
  namespace: togglemaster
  labels:
    app: analytics-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-service
  minReplicaCount: 0
  maxReplicaCount: 10
  cooldownPeriod: 10
  pollingInterval: 15
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.us-west-1.amazonaws.com/775419744057/evaluation-analytics
        queueLength: "5"
        awsRegion: "us-west-1"
        identityOwner: operator
