name: analytics-service CI/CD

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "analytics-service/**"
      - ".github/workflows/analytics-service-ci.yml"
      - ".github/workflows/_ci-python-service.yml"
  push:
    branches: [main]
    paths:
      - "analytics-service/**"
      - ".github/workflows/analytics-service-ci.yml"
      - ".github/workflows/_ci-python-service.yml"

permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/_ci-python-service.yml
    with:
      service_path: analytics-service
      service_name: analytics-service
    secrets: inherit
